Name: eveonlinesettingsmanager
Description: Open source tool Eve Online Settings Manager for EVE Online.
Grade: Gold
Arch: win64

Dependencies:

Parameters:
  
Executable:
  name: Eve Online Settings Manager
  icon: github-mark.png
  file: EVE.Settings.Manager.v1.1.2_windows.exe
  path: Program Files/EVE Settings Manager/EVE.Settings.Manager.v1.1.2_windows.exe

Steps:

- action: run_script
  script: |
    mkdir drive_c/Program\ Files/EVE\ Settings\ Manager
    cd drive_c/Program\ Files/EVE\ Settings\ Manager
    wget -O EVE.Settings.Manager.v1.1.2_windows.exe https://github.com/mintnick/eve-settings-manager/releases/download/v1.1.2/EVE.Settings.Manager.v1.1.2_windows.exe

